### PR TITLE
🚑 Made the team images use GitHub profile pic link

### PR DESCRIPTION
**Pull request by max-programming**
Made the images use GitHub's profile pic link to update the images easily 

## Before:
image

## After:
image

Hopefully, the images are now dynamic

### CODE REVIEW

**Comment by max-programming** [comment]
Let me know if any changes are required

**Comment by BraydenTW** [comment]
Hey @max-programming , thanks for contributing!

Those changes look nice, except if we change our profile pictures again, it wouldn’t work. Those image links you put in are specific to the image of that user. (Their version)

If you want it to dynamically update, I would suggest using the GitHub API.

**Comment by max-programming** [comment]
> Hey @max-programming , thanks for contributing!
> 
> Those changes look nice, except if we change our profile pictures again, it wouldn’t work. Those image links you put in are specific to the image of that user. (Their version)
> 
> If you want it to dynamically update, I would suggest using the GitHub API.

Oh thanks! I'll use the GitHub API and change them. Thanks!

**Comment by BraydenTW** [comment]
@max-programming , sounds good! I have worked with the GitHub API a few times. 

Will we all be able to see it on the website in the end? Will you have to show your GitHub API key? I’m not sure how that works.

**Comment by max-programming** [comment]
> @max-programming , sounds good! I have worked with the GitHub API a few times.
> 
> Will we all be able to see it on the website in the end? Will you have to show your GitHub API key? I’m not sure how that works.

Maybe not the API key but let's see.

**Comment by BraydenTW** [comment]
> > @max-programming , sounds good! I have worked with the GitHub API a few times.
> > Will we all be able to see it on the website in the end? Will you have to show your GitHub API key? I’m not sure how that works.
> 
> Maybe not the API key but let's see. I'll try

True, there’s probably a very easy way to do it. Thanks for you help on this!

**Pull request closed without merging**
